POST https://advogadodigital.onrender.com/login/validacao
Content-Type: application/json

{
    "email": "lucas_moreira@outlook.com",
    "senha": "123456"
}

###


GET https://advogadodigital.onrender.com/login

###

PUT https://advogadodigital.onrender.com/login/5
Content-Type: application/json

{
    "nome": "Santos ferreira",
    "email": "lmsferr@outlook.com"
}

### 

DELETE https://advogadodigital.onrender.com/login/lucas_moreira@outlook.com