POST https://advogadodigital.onrender.com/login/validacao
Content-Type: application/json

{
    "email":"lucas_moreira@outlook.com",
    "senha":"123456"
}

### 

POST https://advogadodigital.onrender.com/tenant
Content-Type: application/json

{
    "nome":"Adwwwgital",
    "responsavel":"lucas",
    "email":"lucas@lucas.com",
    "telefone":"12981559778"
}

###

POST http://localhost:3333/tenant
Content-Type: application/json

{
    "nome":"Adaigital",
    "responsavel":"lucas",
    "email":"lucas@lucas.com",
    "telefone":"12981559778"
}

###

POST http://localhost:3333/clientes
Content-Type: application/json

{
    "tenant": "lucas advogado",
    "nome": "lucas santos",
    "cpf": "31986903826",
    "estadocivil": "solteiro"
}

###

GET http://localhost:3333/clientes

###

GET https://advogadodigital.onrender.com/clientes/Lucas Advocacia

###

GET https://advogadodigital.onrender.com/tenant

###

PUT https://advogadodigital.onrender.com/login/5
Content-Type: application/json

{
    "nome": "Santos ferreira",
    "email": "lmsferr@outlook.com"
}

### 

DELETE https://advogadodigital.onrender.com/login/lucas_moreira@outlook.com